#!/usr/bin/env node
/*
 * build-library.js
 *
 * 扫描仓库根目录下的 library/ 文件夹，把每个子文件夹当作一个「合集」，
 * 生成 assets/js/library-data.js（一个全局 libraryData 数组）供 library.html 渲染。
 *
 * 用法：在仓库根目录运行
 *   node scripts/build-library.js
 *
 * 重要：每次在 library/ 里增删/重命名文件后都要重新运行本脚本，否则页面不会更新。
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LIBRARY_DIR = path.join(ROOT, 'library');
const OUTPUT_FILE = path.join(ROOT, 'assets', 'js', 'library-data.js');

// 跳过的文件名（隐藏文件、系统文件、元数据文件）
function isIgnored(name) {
  return name.startsWith('.') || name === '_meta.json';
}

function formatSize(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB', 'TB'];
  let value = bytes / 1024;
  let i = 0;
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024;
    i++;
  }
  // 小于 10 的保留一位小数，否则取整
  const rounded = value < 10 ? Math.round(value * 10) / 10 : Math.round(value);
  return `${rounded} ${units[i]}`;
}

// 按路径段逐段编码，避免文件名含 # ? % 等字符时断链
function encodePath(...segments) {
  return segments.map(encodeURIComponent).join('/');
}

function getExt(name) {
  const dot = name.lastIndexOf('.');
  return dot > 0 ? name.slice(dot + 1).toLowerCase() : '';
}

// 可选：读取合集文件夹内的 _meta.json，覆盖标题/描述
function readMeta(dirPath) {
  const metaPath = path.join(dirPath, '_meta.json');
  if (!fs.existsSync(metaPath)) return {};
  try {
    return JSON.parse(fs.readFileSync(metaPath, 'utf8'));
  } catch (err) {
    console.warn(`  ! 无法解析 ${metaPath}：${err.message}`);
    return {};
  }
}

function build() {
  if (!fs.existsSync(LIBRARY_DIR)) {
    console.error(`未找到 library/ 目录：${LIBRARY_DIR}`);
    console.error('请先创建 library/<合集名>/ 并放入文件。');
    process.exit(1);
  }

  const entries = fs
    .readdirSync(LIBRARY_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !isIgnored(e.name))
    .sort((a, b) => a.name.localeCompare(b.name, 'zh-Hans-CN'));

  const collections = [];

  for (const dirent of entries) {
    const folderName = dirent.name;
    const dirPath = path.join(LIBRARY_DIR, folderName);
    const meta = readMeta(dirPath);

    const files = fs
      .readdirSync(dirPath, { withFileTypes: true })
      .filter((e) => e.isFile() && !isIgnored(e.name))
      .sort((a, b) => a.name.localeCompare(b.name, 'zh-Hans-CN'))
      .map((e) => {
        const stat = fs.statSync(path.join(dirPath, e.name));
        return {
          name: e.name,
          path: encodePath('library', folderName, e.name),
          ext: getExt(e.name),
          size: stat.size,
          sizeLabel: formatSize(stat.size),
        };
      });

    if (files.length === 0) continue; // 跳过空合集

    collections.push({
      name: meta.title || folderName,
      desc: meta.desc || '',
      files,
    });
  }

  const out =
    `// AUTO-GENERATED by scripts/build-library.js — do not edit by hand.\n` +
    `// 重新生成：在仓库根目录运行  node scripts/build-library.js\n` +
    `const libraryData = ${JSON.stringify(collections, null, 2)};\n`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, out, 'utf8');

  const fileCount = collections.reduce((n, c) => n + c.files.length, 0);
  console.log(`✓ 已生成 ${path.relative(ROOT, OUTPUT_FILE)}`);
  console.log(`  ${collections.length} 个合集，共 ${fileCount} 个文件。`);
}

build();
